### PR TITLE
Merge UI categories into main lausius

### PR DESCRIPTION
**Pull request by Lausius**
fixed merge conflicts in qave's branch :)

### CODE REVIEW

**Review by Qave — APPROVED** [review]

**Review by Noitcereon — CHANGES_REQUESTED** [review]
I get a FOUC (Flash of Unstyled Content) when going to /categories and /audiences. It should be corrected before merging with main.

**Review by Qave — DISMISSED** [review]
intet er bricked xD der findes dog nogle css links etc som der ikke er nødvendige. xD

**Review by Noitcereon — DISMISSED** [review]
¯\_(ツ)_/¯

**Review by Qave — APPROVED** [review]

**Review by Noitcereon — APPROVED** [review]
¯\_(ツ)_/¯

**Pull request merged**
